stages:
  - security

security-secrets:
  stage: security
  allow_failure: false
  image: alpine:3.23.3@sha256:25109184c71bdad752c8312a8623239686a9a2071e8825f20acb8f2198c3f659
  variables:
    SCAN_PATH: "." 
  before_script:
    - apk add --no-cache git curl jq
    - curl -sSfL https://raw.githubusercontent.com/trufflesecurity/trufflehog/main/scripts/install.sh | sh -s -- -b /usr/local/bin
  script:
    - trufflehog filesystem "$SCAN_PATH" --results=verified,unknown --fail --json | jq
#  rules:
#    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
