stages:
  - security

security-secrets:
  stage: security
  allow_failure: false
  image: alpine:3.23.2@sha256:865b95f46d98cf867a156fe4a135ad3fe50d2056aa3f25ed31662dff6da4eb62
  variables:
    SCAN_PATH: "." 
  before_script:
    - apk add --no-cache git curl jq
    - curl -sSfL https://raw.githubusercontent.com/trufflesecurity/trufflehog/main/scripts/install.sh | sh -s -- -b /usr/local/bin
  script:
    - trufflehog filesystem "$SCAN_PATH" --results=verified,unknown --fail --json | jq
#  rules:
#    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
