apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: ingress-nginx
  labels:
    snofox.net/catagory: system
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  sources:
    - repoURL: https://kubernetes.github.io/ingress-nginx
      # https://github.com/kubernetes/ingress-nginx?tab=readme-ov-file#supported-versions-table
      chart: ingress-nginx
      targetRevision: 4.14.1
      helm:
        valueFiles:
        - $values/values/ingress-nginx.yml
    - repoURL: https://gitlab.com/SnoFox/kubernetes.git
      targetRevision: master
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
