apiVersion: crd.projectcalico.org/v1
kind: FelixConfiguration
metadata:
  annotations:
    operator.tigera.io/bpfEnabled: "false"
  name: default
spec:
  logSeverityScreen: Info
  bpfEnabled: false
  bpfLogLevel: ""
  healthPort: 9099
  ipipEnabled: true
  # default is 0xffff0000, which conflicts with Tailscale
  # apply 0x00ffff00 instead
  nftablesMarkMask: 16776960
  reportingInterval: 0s
  vxlanVNI: 4096
  logFilePath: "none"
  prometheusMetricsEnabled: true
  prometheusWireGuardMetricsEnabled: false
