apiVersion: crd.projectcalico.org/v1
kind: FelixConfiguration
metadata:
  annotations:
    operator.tigera.io/bpfEnabled: "true"
  name: default
spec:
  logSeverityScreen: Info
  bpfEnabled: true
  ipipEnabled: false
  vxlanEnabled: false
  bpfLogLevel: ""
  healthPort: 9099
  # default is 0xffff0000, which conflicts with Tailscale
  # apply 0xff00ff00 instead
  iptablesMarkMask: 4278255360
  reportingInterval: 0s
  vxlanVNI: 4096
  logFilePath: "none"
  prometheusMetricsEnabled: true
  prometheusWireGuardMetricsEnabled: false
