---
kind: ConfigMap
apiVersion: v1
metadata:
  namespace: tandoor
  labels:
    app: recipes
  name: tandoor-config
data:
  DEBUG: "0"
  ALLOWED_HOSTS: '*'
  GUNICORN_MEDIA: "0"
  DB_ENGINE: django.db.backends.postgresql
  POSTGRES_HOST: recipes-pg-rw
  POSTGRES_PORT: "5432"
  POSTGRES_DB: recipes
---
kind: ConfigMap
apiVersion: v1
metadata:
  namespace: tandoor
  labels:
    app: recipes
  name: recipes-nginx-config
data:
  nginx-config: |-
    pid        /tmp/nginx.pid;
    events {
      worker_connections 1024;
    }
    http {
      proxy_temp_path /tmp/proxy_temp;
      client_body_temp_path /tmp/client_temp;
      server {
        listen 8080;
        server_name _;
        client_max_body_size 512M;
        location /media {
          alias /media/;
          add_header Content-Disposition 'attachment; filename="$args"';
        }
        location = /service-worker.js {
          alias /static/vue3/service-worker.js;
        }
        # pass requests for dynamic content to gunicorn
        location / {
          proxy_set_header Host $http_host;
          proxy_pass http://localhost:8081;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        location /errors/ {
          alias /etc/nginx/http.d/errorpages/;
          internal;
        }
      }
    }

