apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
 - https://github.com/argoproj/argo-cd//manifests/cluster-install?ref=v3.2.3
 - resources/ingress.yaml
patches:
  - path: patches/argocd-cm.yaml
